### PR TITLE
Watch new / removed page files

### PR DESCRIPTION
**Pull request by rixo**
Add an option to watch pages directory to rebuild when routes are added / deleted, as discussed in Discord.

In my setup, compatible with HMR :)

I based on my earlier PR, so this also includes a bit of refactor.

### CODE REVIEW

**Comment by rixo** [comment]
Just realized I forgot to test the other case, without the watch option... Coming back to this soon.

**Comment by rixo** [comment]
OK I think it should be good both in watch or non watch mode.

I've changed the default watch value to `process.env.ROLLUP_WATCH`, to not be watching the routes when Rollup itself won't be watching...

**Comment by wuliupo** [comment]
Is it not supported HMR where new page was added or delete a page file?

**Comment by jakobrosenberg** [comment]
Are you using R3 or R2?

**Pull request closed without merging**
