### PR TITLE
fix: point Router type in index.d.ts to Router.svelte

### LINKED ISSUE #248: JSX element type 'Router' does not have any construct or call signatures.ts(2604)
**bug description**

I followed the instructions to [install Routify to existing project](https://routify.dev/guide/installation/install-to-existing-project), which is Svelte with (official) TypeScript and in VSCode I get the following error under Router component:

```txt
JSX element type 'Router' does not have any construct or call signatures.ts(2604)
```
_npm run dev_ runs just fine and reports no errors. Same is for _npm run build_.

**package.json**

```
    "build": "routify -b && rollup -c",
    "dev": "routify -c svelte-dev",
    "svelte-dev": "rollup -c -w",
    "start": "sirv public --single",
    "validate": "svelte-check"
```

**version**

Routify 1.9.7
Svelte 3.24.1

**App.svelte**

```
<script type="ts">
  import { Router } from "@sveltech/routify";
  import { routes } from "@sveltech/routify/tmp/routes";
</script>

<Router {routes} />
```

### PR DESCRIPTION
**Pull request by gustavopch**
Fixes https://github.com/roxiness/routify/issues/248.

### CODE REVIEW

**Comment by jakobrosenberg** [comment]
Beautiful. 👍

**Comment by guidobouman** [comment]
@jakobrosenberg Is there a reason why you're only releasing pre-releases lately? (Both on the 2.7.x & 2.8.x branches)

2.7.3 is marked as latest. So we're not receiving this patch.

**Comment by jakobrosenberg** [comment]
@guidobouman there have been some changes which which were hard to test, so I've been somewhat conservative in pushing to stable.

However, I think with the recent bug fixes we should be able to push it to stable.

**Pull request merged**
