### PR TITLE
WIP - Using Svelte Context API's for deeply accessible helpers & router state

### PR DESCRIPTION
**Pull request by matthewrobb**
~~The inspiration for this PR came from the issue I detailed in #15. The changes are as follows and would likely require updates to documentation etc.~~

~~The rollup plugin now generates as `'svelte-filerouter/routes'`. Most of the logic in `navigate.js` has moved into `store.js` and is now fully reactive by default. The generated routes module now looks something like:~~

```js
import * as router from 'svelte-filerouter';

export const routes = [...];
export const options = {...};

router.options.set(options);
router.routes.set(routes);
```
~~Documentation would need to be updated to state that your application needs to `import 'svelte-filerouter/routes'` in order to for routing to work.~~

### CODE REVIEW

**Comment by matthewrobb** [comment]
@jakobrosenberg Looking for feedback as to whether or not this is in conflict with the general direction of the library?

**Comment by jakobrosenberg** [comment]
@matthewrobb any chance this can be done without the use of store? Or can you test that it doesn't fall victim to this bug?
https://github.com/sveltejs/svelte/issues/3685

I'm planning a v2 and consider to use the url helper strictly as a prop, so it can be context aware.
https://github.com/jakobrosenberg/svelte-filerouter/issues/19

**Comment by matthewrobb** [comment]
@jakobrosenberg This can definitely be done without a store. I think the store solution is elegant but in the light of that bug I will rework it to go a different way. That's a very unfortunate bug.

**Comment by jakobrosenberg** [comment]
Yes, horrible bug. Speculating, I'd say that most people who use transitions aren't aware of the bug's cause and simply end up disabling their transitions. At least that's what I've observed on discord. (Are you on there by any chance?)

What do you think about simply using setContext for all (except user defined) props in v2?

**Comment by matthewrobb** [comment]
@jakobrosenberg I think using setContext for most of this stuff is perfect and any props passed into Router at the root can easily get passed to routed components like so:

```
<svelte:component {...$$props} />
```

**Pull request closed without merging**
