### PR TITLE
Fixed ID parsing problem with different css querySelector

### PR DESCRIPTION
**Pull request by petermakeswebsites**
I'm not sure if you're still supporting v2 for bug fixes, and I also haven't checked if this is a thing in v3. I'm using v2 currently on quite a large application so it would be cool to have this updated for v2 as well.

Basically what was happening was although the IDs were passing the regExp id validation `/^[A-Za-z]+[\w\-\:\.]*$/` which as far as I know properly works to validate an ID selector, what was happening was the css selector in `querySelector` was throwing errors with certain patterns even though they did validate the regexp test (for example: `T-6.I.21`). Easily corrected using a different style of css query.

Note I haven't actually tested this because to get this on my app through npm sounds like a lot of work.

### CODE REVIEW

**Comment by ghostdevv** [comment]
v2 is still our main stable release, v3 is in BETA! will get jake to take a look at this as it's his area

**Comment by petermakeswebsites** [comment]
I simplified it more and it made the regex check unnecessary because `getElementById` will return null (rather than throw an error) even if the ID is malformed

**Review by ghostdevv — APPROVED** [review]
LGTM

**Comment by jakobrosenberg** [comment]
Before I merge this. Can either of you comment on the purpose/importance of https://github.com/roxiness/routify/pull/234 ?

**Comment by petermakeswebsites** [comment]
#234 had a purpose when it was using querySelector as a means to get the element because a malformed ID would have thrown an uncaught error. However some properly formed IDs that pass the validation actually throw an error with querySelector anyway simply because of CSS selector syntax (reference first post). So the regex validation offered some protection against errors but not all.

My first commit patched the issue by changing the querySelector query to query the ID attribute rather than using hash. This made it so errors would be impossible.

I was doing a meditation the next day and in the midst of a quiet mind the thought of getElementById came to me, which doesn't throw an error at all and just returns null if it's malformed. So it doesn't need any kind of regex protection at all.

**Comment by jakobrosenberg** [comment]
Thanks for PR @petermakeswebsites.

**Pull request merged**
