### PR TITLE
Fix #320

### LINKED ISSUE #320: Impossible to disable code splitting build
**Bug description**
Prior to 2.10.1, the default value for the code splitting option was false, thereby the -D option could be used to enable it. However, after 2.10.1, the default value was changed to true, but there is absolutely no way to set it back to false. `-D false` does nothing, as it was specified as an option without a parameter in the commander setup.

Is this an intentional breaking change? Semver would indicate that 2.8 -> 2.10 should not be breaking, but unfortunately it is. If it is intentional, the `-D` option should probably be removed or marked as deprecated since it no longer does anything. If it is not intentional, the option should either accept a parameter to allow setting it to false, or another "--no-dynamic-imports" or "--static-imports" should be added to disable it.

Although changing to a code splitting build in rollup is possible, it is not ideal for all applications.

**version**
Routify 2.10.1

### PR DESCRIPTION
**Pull request by rsheasby**

### CODE REVIEW

**Comment by jakobrosenberg** [comment]
Thanks for the PR @rsheasby. I've updated the existing `-D` to reflect the defaults of v2. `commanderjs` does some magic where it it uses `false` instead of `true` when you prefix the string with `--no-`

**Comment by rsheasby** [comment]
@jakobrosenberg the magic that uses false instead of true when prefixing with --no- only works when you actually add the `--no-dynamic-imports` option to the config, as my PR would implement. Try it for yourself and you'll see that `--no-dynamic-imports` does *not* work in the current version:

error: unknown option '--no-dynamic-imports'

**Comment by rsheasby** [comment]
As you can see in the commander.js documentation, adding a second `--no-` prefixed option is the correct way to allow negation.

https://github.com/tj/commander.js/#other-option-types-negatable-boolean-and-booleanvalue

**Comment by rsheasby** [comment]
Oh, apologies I didn't actually look at your change. I see now how you implemented it. That should work perfectly, thanks.
I personally would take objection with changing the meaning of a shorthand flag to the exact opposite in an update, which is why my PR added a separate flag, but that's up to you I guess.

**Pull request closed without merging**
