### PR TITLE
feat(config) read config from files, add options for filtering and sorting children during build

### PR DESCRIPTION
**Pull request by dominikg**

### CODE REVIEW

**Comment by jakobrosenberg** [comment]
@dominikg thanks for your PR. I'm currently in the process of rewriting the config handling of Routify so we'll probably have to review and revise the PR after it after.

Please note that Commander doesn't discriminate between defaults and user defined values, meaning that when you run program.opts() it will return an object with all options and you have no way of telling which were set by the user and which were taken from defaults. This makes it impossible to merge the configs directly.

One solution to this problem is to use the config files as defaults for commander. This creates a paradox as we need commander to resolve the config file and we need the config file to set the defaults for commander.

**Comment by dominikg** [comment]
I filtered out default values from cli opts and added hashScroll: true to defaults to avoid that, but now that i'm writing it here I think I created a situation where the user now has to specify both noXxx and XXX options to get a clean config. gotta read up on commander opts....

**Comment by Wolfr** [comment]
Is it correct that @dominikg 's "feat(config) read config from files" was added in 1.7 @jakobrosenberg ?

**Comment by jakobrosenberg** [comment]
@Wolfr no, the PR has not been merged as it coincided with my own code. It seems we were both rewriting the config handling at the same time.

**Comment by dominikg** [comment]
yes! 
I'm closing this one and might open another one later for filtering/sorting.

**Comment by jakobrosenberg** [comment]
@dominikg I'm writing an extensions/plugins module at the moment. Would you have to talk on Discord later today about how to best handle file sorting/filtering?

**Comment by Wolfr** [comment]
Yes I realized you were both writing the same feature. I am just asking for my understanding for my next update on Routify (3rd blog post) :)

**Comment by jakobrosenberg** [comment]
@Wolfr in that case, the rewrite allows for configuration through (in order of precedence):
- CLI
- environment variables / .env file
- routify.config.js

I've added JSON5 and YAML to Routify to handle legacy config files in the config folder. Configuration through Rollup is untouched.

**Pull request closed without merging**
