### PR TITLE
Move sorting of child pages to build time.

### PR DESCRIPTION
**Pull request by colinbate**
Here is the change to sort child pages at build time. I've changed the sorting logic slightly to sort on `index`, `title` and `path` separately. This supports negative indexes properly.

Also, I've created a hook to provide an alternative sort method in the config file if desired. Not sure if this is something you want to have, if not, it is easy to remove.

Also I'm not sure what state the unit tests are in, they don't seem to run. I have tested the changes manually.

### CODE REVIEW

**Comment by jakobrosenberg** [comment]
I just remembered why sorting was done clientside. The routes list is a store and can be updated or merged with other lists. Shouldn't matter much though. ^^

**Comment by colinbate** [comment]
Yea I think that’s fine. I think if people make changes to that list client side then those changes should be reflected with out further sorting, this just provides a default sorting which the consumer has control over (with index).

**Pull request merged**
